### ISSUE TITLE
Compagnion App doesn't work anymore

### ISSUE THREAD

**Issue by DenDuze** [edgiardina/Ifpa#132]
For a few weeks I noticed that the app doesn't work anymore on Android version 9
It always worked perfect before the covid-shit but now that the tournaments again start I wanted to check the data again and it does not work anymore.
I can't find any player or tournament list, all my stats are gone
I already removed the program for my phone and re-installed the app but still nothing.
What can be the reason? 
Is there some setting so we can produce some logging to find out what's the reason for this malfunction?

Regards
Didier

**Comment by edgiardina** [comment]
The IFPA app uses Lets Encrypt certificates. The certificate provider recently lost top level certification or something. So Android doesn’t trust the ifpa api anymore. I have raised an issue with the ifpa api owner and am trying to get a resolution asap. Sorry!
