### ISSUE TITLE
Add SCS data to Player Detail

### ISSUE THREAD

**Issue by edgiardina** [edgiardina/Ifpa#17]
And add IFPA number while you're in there.

**Comment by edgiardina** [comment]
Blocked by API data not available

**Comment by smazurov** [comment]
any idea when/if it would ever be available?

**Comment by edgiardina** [comment]
@smazurov no idea. Brian at IFPA is in charge of it. I’ve asked, I know he wants to do a v2 of the API but I think it’s just finding the time.

**Comment by edgiardina** [comment]
Implemented in the branch https://github.com/edgiardina/Ifpa/tree/new-api-changes
waiting for API to come out of beta before merging and deploying
